In [86]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split,GridSearchCV,RandomizedSearchCV
from sklearn import svm
from sklearn.metrics import accuracy_score

In [87]:
df=pd.read_csv('../datasets/diabetes.csv')

In [88]:
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [89]:
df.shape

(768, 9)

In [90]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Pregnancies               768 non-null    int64
 1   Glucose                   768 non-null    int64
 2   BloodPressure             768 non-null    int64
 3   SkinThickness             768 non-null    int64
 4   Insulin                   768 non-null    int64
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64
 8   Outcome                   768 non-null    int64
dtypes: float64(2), int64(7)
memory usage: 54.1 KB

In [91]:
df.describe()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000
mean,3.845052,120.894531,69.105469,20.536458,79.799479,31.992578,0.471876,33.240885,0.348958
std,3.369578,31.972618,19.355807,15.952218,115.244002,7.884160,0.331329,11.760232,0.476951
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.078000,21.000000,0.000000
25%,1.000000,99.000000,62.000000,0.000000,0.000000,27.300000,0.243750,24.000000,0.000000
50%,3.000000,117.000000,72.000000,23.000000,30.500000,32.000000,0.372500,29.000000,0.000000
75%,6.000000,140.250000,80.000000,32.000000,127.250000,36.600000,0.626250,41.000000,1.000000
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000,1.000000

In [92]:
df['Outcome'].value_counts()

Outcome
0    500
1    268
Name: count, dtype: int64

In [93]:
df.groupby('Outcome').mean()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
Outcome,,,,,,,,
0,3.298000,109.980000,68.184000,19.664000,68.792000,30.304200,0.429734,31.190000
1,4.865672,141.257463,70.824627,22.164179,100.335821,35.142537,0.550500,37.067164

In [94]:
# seprate x and y

In [95]:
X=df.drop(columns=['Outcome'],axis=1)
y=df['Outcome']

In [96]:
scaler=StandardScaler()
X_scaled=scaler.fit_transform(X)

In [97]:
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.33, random_state=42)

In [98]:
model=svm.SVC( )

In [99]:
#grid search cv

In [100]:
classifier =GridSearchCV((model),{
    'C':[1,10,20,30],
    'kernel' :['rbf','linear'],
},cv=5,return_train_score=False
                        )

In [101]:
classifier.fit(X_train,y_train)

GridSearchCV(cv=5, estimator=SVC(),
             param_grid={'C': [1, 10, 20, 30], 'kernel': ['rbf', 'linear']})

In [108]:
results = pd.DataFrame(classifier.cv_results_)
results.head()

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.005871,0.000908,0.003097,0.001295,1,rbf,"{'C': 1, 'kernel': 'rbf'}",0.796117,0.737864,0.757282,0.737864,0.754902,0.756806,0.021292,5
1,0.019840,0.022836,0.002727,0.001390,1,linear,"{'C': 1, 'kernel': 'linear'}",0.844660,0.718447,0.825243,0.718447,0.754902,0.772340,0.053183,1
2,0.008306,0.005056,0.002147,0.000193,10,rbf,"{'C': 10, 'kernel': 'rbf'}",0.796117,0.728155,0.728155,0.718447,0.764706,0.747116,0.029160,6
3,0.018284,0.003675,0.001191,0.000043,10,linear,"{'C': 10, 'kernel': 'linear'}",0.844660,0.718447,0.825243,0.699029,0.754902,0.768456,0.057509,2
4,0.006702,0.000489,0.002133,0.000073,20,rbf,"{'C': 20, 'kernel': 'rbf'}",0.786408,0.699029,0.689320,0.708738,0.715686,0.719836,0.034457,7

In [126]:
# get the best model parameter and use
best_model = classifier.best_estimator_

In [127]:
train_predictions=best_model.predict(X_train)

In [128]:
train_accuracy= accuracy_score(y_train,train_predictions)

In [129]:
train_accuracy

0.7821011673151751

In [130]:
### test accuracy

In [132]:
test_predictions=best_model.predict(X_test)
test_accuracy= accuracy_score(y_test,test_predictions)
test_accuracy

0.7519685039370079

In [133]:
# prediction Function

In [147]:
def dibetes_predictor (data):
    arrayData=np.array(data).reshape(1,-1)
    pred=best_model.predict(arrayData)
    if (pred[0] == 0):
        return'The person is not diabetic'
    else:
        return'The person is diabetic'

In [148]:
input_data = (5,166,72,19,175,25.8,0.587,51)

In [149]:
diabetic_patient=dibetes_predictor(input_data)

In [150]:
diabetic_patient

'The person is diabetic'

In [151]:
# export pkl files

In [153]:
import joblib
joblib.dump(best_model,'./models/diabetic_model.pkl')
joblib.dump(scaler,'./models/scaler.pkl')
joblib.dump(X.columns.tolist(),'./models/columns.pkl')

['./models/columns.pkl']